owner: kmushi-coin
repo: status

sites:
  - name: Website
    url: https://kmushicoin.co
  - name: API - SEND
    url: https://new.kmushicoin.co
  - name: Explorer
    url: https://explorer.kmushicoin.co

status-website:
  cname: status.kmushicoin.co
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: KTV Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status Kmushicoin real time
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
