owner: kmushi-coin
repo: status

sites:
  - name: Website - KmushiPay
    url: https://kmushicoin.co/api/ping
    body: 'pong'
  - name: API - SEND
    url: https://new.kmushicoin.co/ping
    body: 'pong'
  - name: Explorer
    url: https://explorer.kmushicoin.co/api
  - name: Electrumx
    check: "tcp-ping"
    url: electrumx.kmushicoin.co
    port: 36599
  - name: VPS 3
    check: "tcp-ping"
    url: ghos3.kmushicoin.co
    port: 36599
  - name: VPS 4
    check: "tcp-ping"
    url: ghos4.kmushicoin.co
    port: 36599
  - name: VPS 5
    check: "tcp-ping"
    url: ghos5.kmushicoin.co
    port: 36599
  - name: VPS 6
    check: "tcp-ping"
    url: ghos6.kmushicoin.co
    port: 36599
  

status-website:
  cname: status.kmushicoin.co
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: KTV Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status Kmushicoin real time
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
